// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZCaaq5YJrWULwHJ9Ue6fDLDVegn_uTcg',
    appId: '1:398205899863:web:b0708f8302879a53cb7f12',
    messagingSenderId: '398205899863',
    projectId: 'flutter-login-4f7b7',
    authDomain: 'flutter-login-4f7b7.firebaseapp.com',
    storageBucket: 'flutter-login-4f7b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoMdcSL5jI75ZY70jZHZsHtDHgtgyaE8k',
    appId: '1:398205899863:android:0eb91805c42f4ec2cb7f12',
    messagingSenderId: '398205899863',
    projectId: 'flutter-login-4f7b7',
    storageBucket: 'flutter-login-4f7b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNK7qYceln_4lUV4ApZzxse6bsmRkt2h8',
    appId: '1:398205899863:ios:592f79b9d4b4b0b9cb7f12',
    messagingSenderId: '398205899863',
    projectId: 'flutter-login-4f7b7',
    storageBucket: 'flutter-login-4f7b7.appspot.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNK7qYceln_4lUV4ApZzxse6bsmRkt2h8',
    appId: '1:398205899863:ios:c220927657e3915bcb7f12',
    messagingSenderId: '398205899863',
    projectId: 'flutter-login-4f7b7',
    storageBucket: 'flutter-login-4f7b7.appspot.com',
    iosBundleId: 'com.example.flutterLogin.RunnerTests',
  );
}
